import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as bcrypt from 'bcrypt';
import 'dotenv/config';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding database with default user and full demo dataset...');

  const passwordHash = await bcrypt.hash('Password@123', 10);

  const user = await prisma.user.upsert({
    where: { email: 'karan@gmail.com' },
    update: {},
    create: {
      email: 'karan@gmail.com',
      passwordHash,
      name: 'Sacher Family',
    },
  });

  console.log(`User: ${user.name} (${user.email})`);

  // Create account for user with opening balance
  const account = await prisma.account.upsert({
    where: { id: `account_${user.id}` },
    update: { openingBalance: 97809.04 },
    create: {
      id: `account_${user.id}`,
      userId: user.id,
      name: 'Primary Account',
      openingBalance: 97809.04,
      currency: 'INR',
    },
  });

  console.log(
    `Account created: ${account.name} with opening balance ₹${account.openingBalance}`,
  );

  // Clear existing data for this user (keep user/account intact)
  await prisma.loan.deleteMany({ where: { userId: user.id } });
  await prisma.investment.deleteMany({ where: { userId: user.id } });
  await prisma.insurance.deleteMany({ where: { userId: user.id } });
  await prisma.transaction.deleteMany({ where: { userId: user.id } });

  // Seed loans (sourced from live DB data)
  await prisma.loan.createMany({
    data: [
      {
        userId: user.id,
        name: 'Car Loan',
        lender: 'SBI',
        principal: 990000,
        interestRate: 7.75,
        interestType: 'COMPOUND',
        emi: 19957,
        outstanding: 266211,
        startDate: new Date('2022-09-07T00:00:00.000Z'),
        endDate: new Date('2027-08-07T00:00:00.000Z'),
        type: 'INTEREST_BEARING',
      },
      {
        userId: user.id,
        name: 'Personal Loan HDFC',
        lender: 'HDFC',
        principal: 870400,
        interestRate: 11,
        interestType: 'COMPOUND',
        emi: 22496,
        outstanding: 734849,
        startDate: new Date('2025-10-07T00:00:00.000Z'),
        endDate: new Date('2029-10-07T00:00:00.000Z'),
        type: 'INTEREST_BEARING',
      },
      {
        userId: user.id,
        name: 'Sewing Loan',
        lender: 'Loard Krishna',
        principal: 72000,
        interestRate: 0,
        interestType: 'COMPOUND',
        emi: 6000,
        outstanding: 54000,
        startDate: new Date('2026-04-07T00:00:00.000Z'),
        endDate: new Date('2027-03-07T00:00:00.000Z'),
        type: 'INTEREST_BEARING',
      },
      {
        userId: user.id,
        name: 'Personal Loan ICICI',
        lender: 'ICICI',
        principal: 1500000,
        interestRate: 10.6,
        interestType: 'COMPOUND',
        emi: 28403,
        outstanding: 1469560,
        startDate: new Date('2026-05-05T00:00:00.000Z'),
        endDate: new Date('2032-05-05T00:00:00.000Z'),
        type: 'INTEREST_BEARING',
      },
    ],
  });
  console.log(`Seeded ${4} loans.`);

  // Seed mutual fund investments, including SIP tracking (sourced from live DB data)
  await prisma.investment.createMany({
    data: [
      {
        userId: user.id,
        name: 'SBI ELSS Tax Saver Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 45498,
        units: null,
        navOrPrice: 20.83,
        isSip: false,
        sipAmount: null,
        purchaseDate: new Date('2023-01-01T00:00:00.000Z'),
        value: 51835,
        profit: 6337,
      },
      {
        userId: user.id,
        name: 'Quant ELSS Tax Saver Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 53523,
        units: null,
        navOrPrice: 212.74,
        isSip: false,
        sipAmount: null,
        purchaseDate: new Date('2023-01-01T00:00:00.000Z'),
        value: 66643,
        profit: 13120,
      },
      {
        userId: user.id,
        name: 'Motilal Oswal Multi Cap Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 19694,
        units: null,
        navOrPrice: 105,
        isSip: true,
        sipAmount: 1000,
        purchaseDate: new Date('2023-06-01T00:00:00.000Z'),
        value: 26036,
        profit: 6342,
      },
      {
        userId: user.id,
        name: 'UTI Nifty 50 Index Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 8000,
        units: null,
        navOrPrice: 35.12,
        isSip: true,
        sipAmount: 2000,
        purchaseDate: new Date('2024-01-01T00:00:00.000Z'),
        value: 8239,
        profit: 239,
      },
      {
        userId: user.id,
        name: 'Bandhan Small Cap Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 5000,
        units: null,
        navOrPrice: 8.69,
        isSip: false,
        sipAmount: null,
        purchaseDate: new Date('2024-01-01T00:00:00.000Z'),
        value: 5298,
        profit: 298,
      },
      {
        userId: user.id,
        name: 'Parag Parikh Flexi Cap Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 6000,
        units: null,
        navOrPrice: 28.79,
        isSip: true,
        sipAmount: 1500,
        purchaseDate: new Date('2024-01-01T00:00:00.000Z'),
        value: 6100,
        profit: 100,
      },
      {
        userId: user.id,
        name: 'Canara Robeco Small Cap Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 4000,
        units: null,
        navOrPrice: 8.67,
        isSip: true,
        sipAmount: 1000,
        purchaseDate: new Date('2024-06-01T00:00:00.000Z'),
        value: 4325,
        profit: 325,
      },
      {
        userId: user.id,
        name: 'Motilal Oswal Midcap Fund Direct Growth',
        type: 'MUTUAL_FUND',
        principal: 4000,
        units: null,
        navOrPrice: 4.36,
        isSip: false,
        sipAmount: null,
        purchaseDate: new Date('2024-06-01T00:00:00.000Z'),
        value: 4311,
        profit: 311,
      },
    ],
  });
  console.log(`Seeded ${8} investments.`);

  // Seed insurance policies (sourced from live DB data)
  await prisma.insurance.createMany({
    data: [
      {
        userId: user.id,
        policyName: 'LIC Karan 1',
        policyNumber: '165545344',
        type: 'LIFE',
        premium: 1777,
        premiumFrequency: 'QUARTERLY',
        renewalDate: new Date('2026-07-22T00:00:00.000Z'),
        nominee: 'Kiran Bala',
        coverage: 200000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'Tata Term Insurance',
        policyNumber: 'C232104075',
        type: 'LIFE',
        premium: 17228,
        premiumFrequency: 'YEARLY',
        renewalDate: new Date('2026-08-25T00:00:00.000Z'),
        nominee: 'Kiran Bala',
        coverage: 5000000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'LIC Karan 2',
        policyNumber: '165729433',
        type: 'LIFE',
        premium: 5425,
        premiumFrequency: 'HALF_YEARLY',
        renewalDate: new Date('2026-09-08T00:00:00.000Z'),
        nominee: 'Kiran Bala',
        coverage: 200000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'LIC Mom',
        policyNumber: '165729578',
        type: 'LIFE',
        premium: 6530,
        premiumFrequency: 'HALF_YEARLY',
        renewalDate: new Date('2026-09-08T00:00:00.000Z'),
        nominee: 'Karan Kumar',
        coverage: 200000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'Bike Insurance',
        policyNumber: 'HIMLINS',
        type: 'VEHICLE',
        premium: 9000,
        premiumFrequency: 'YEARLY',
        renewalDate: new Date('2026-09-10T00:00:00.000Z'),
        nominee: null,
        coverage: 300000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'Gagan Policy 1',
        policyNumber: 'GGNPOL',
        type: 'LIFE',
        premium: 11747,
        premiumFrequency: 'YEARLY',
        renewalDate: new Date('2027-06-11T00:00:00.000Z'),
        nominee: 'Karan Kumar',
        coverage: 200000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'Gagan Policy 2',
        policyNumber: 'GGNPOL2',
        type: 'LIFE',
        premium: 9335,
        premiumFrequency: 'YEARLY',
        renewalDate: new Date('2027-06-12T00:00:00.000Z'),
        nominee: 'Karan Kumar',
        coverage: 200000,
        status: 'ACTIVE',
      },
      {
        userId: user.id,
        policyName: 'Car Insurance',
        policyNumber: 'CARINS',
        type: 'VEHICLE',
        premium: 12000,
        premiumFrequency: 'YEARLY',
        renewalDate: new Date('2027-06-30T00:00:00.000Z'),
        nominee: null,
        coverage: 760000,
        status: 'ACTIVE',
      },
    ],
  });
  console.log(`Seeded ${8} insurance policies.`);

  // Seed transactions (sourced from live DB data)
  await prisma.transaction.createMany({
    data: [
      {
        userId: user.id,
        date: new Date('2026-06-01T06:30:00.000Z'),
        description: 'Seerat Deduction',
        category: 'Investment',
        subCategory: null,
        amount: 1000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-03T06:30:00.000Z'),
        description: 'Samose',
        category: 'Food',
        subCategory: null,
        amount: 120,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-03T06:30:00.000Z'),
        description: 'Elect Bill',
        category: 'Utilities',
        subCategory: null,
        amount: 821,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-03T06:30:00.000Z'),
        description: 'Elect Bill',
        category: 'Utilities',
        subCategory: null,
        amount: 1688,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-03T06:30:00.000Z'),
        description: 'Cloth',
        category: 'Clothes',
        subCategory: null,
        amount: 50,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-03T06:30:00.000Z'),
        description: 'Dal',
        category: 'Misc',
        subCategory: null,
        amount: 60,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-05T06:30:00.000Z'),
        description: 'Emi Personal',
        category: 'Loan',
        subCategory: null,
        amount: 28403,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-05T06:30:00.000Z'),
        description: 'Gagan EMI',
        category: 'Loan',
        subCategory: null,
        amount: 6000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-05T06:30:00.000Z'),
        description: 'Salary Incoming',
        category: 'Salary',
        subCategory: null,
        amount: 130896,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-07T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 850,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-07T06:30:00.000Z'),
        description: 'EMI Personal',
        category: 'Loan',
        subCategory: null,
        amount: 22496,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 120,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Gagan',
        category: 'Misc',
        subCategory: null,
        amount: 5000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 1102.8,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 60,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 120,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 100,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 120,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Cake',
        category: 'Food',
        subCategory: null,
        amount: 420,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Income',
        category: 'Misc',
        subCategory: null,
        amount: 200,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Generic Expense',
        category: 'Misc',
        subCategory: null,
        amount: 200,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-08T06:30:00.000Z'),
        description: 'Pastry',
        category: 'Food',
        subCategory: null,
        amount: 150,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-09T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 1292,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-09T06:30:00.000Z'),
        description: 'Namkeen',
        category: 'Misc',
        subCategory: null,
        amount: 150,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-10T06:30:00.000Z'),
        description: 'EMI Car',
        category: 'Loan',
        subCategory: null,
        amount: 19957,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-10T06:30:00.000Z'),
        description: 'MD Eid',
        category: 'Misc',
        subCategory: null,
        amount: 501,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-10T06:30:00.000Z'),
        description: 'Tarun',
        category: 'Medical',
        subCategory: null,
        amount: 205,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 3400,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'SIP',
        category: 'Investment',
        subCategory: null,
        amount: 1500,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'SIP',
        category: 'Investment',
        subCategory: null,
        amount: 1000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'SIP',
        category: 'Investment',
        subCategory: null,
        amount: 1000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'SIP',
        category: 'Investment',
        subCategory: null,
        amount: 2000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-11T06:30:00.000Z'),
        description: 'Phone Bill',
        category: 'Utilities',
        subCategory: null,
        amount: 1500,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-12T06:30:00.000Z'),
        description: 'LIC',
        category: 'Gagan',
        subCategory: null,
        amount: 11747,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-12T06:30:00.000Z'),
        description: 'Liquor',
        category: 'Liquor',
        subCategory: null,
        amount: 1440,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-12T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 1331,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-12T06:30:00.000Z'),
        description: 'Gopal Sweets',
        category: 'Food',
        subCategory: null,
        amount: 780,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-12T06:30:00.000Z'),
        description: 'LIC',
        category: 'Gagan',
        subCategory: null,
        amount: 9335,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-13T06:30:00.000Z'),
        description: 'Gagan',
        category: 'Misc',
        subCategory: null,
        amount: 5000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-13T06:30:00.000Z'),
        description: 'Amazon',
        category: 'Shopping',
        subCategory: null,
        amount: 493,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-14T06:30:00.000Z'),
        description: 'Radhika',
        category: 'Misc',
        subCategory: null,
        amount: 2800,
        type: 'INCOME',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-14T06:30:00.000Z'),
        description: 'Radhika',
        category: 'Misc',
        subCategory: null,
        amount: 1400,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-14T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 3491,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-16T06:30:00.000Z'),
        description: 'Tea',
        category: 'Misc',
        subCategory: null,
        amount: 40,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-18T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 90,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-18T06:30:00.000Z'),
        description: 'Car Service',
        category: 'Misc',
        subCategory: null,
        amount: 5621,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-18T06:30:00.000Z'),
        description: 'liquor',
        category: 'Liquor',
        subCategory: null,
        amount: 1100,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-18T06:30:00.000Z'),
        description: 'liquor',
        category: 'Liquor',
        subCategory: null,
        amount: 1120,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-19T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 187.95,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-19T06:30:00.000Z'),
        description: 'Auto',
        category: 'Misc',
        subCategory: null,
        amount: 270,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-22T06:30:00.000Z'),
        description: 'Cash Travel',
        category: 'Misc',
        subCategory: null,
        amount: 3500,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-23T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 331,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-23T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 210,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-23T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 104,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-24T06:30:00.000Z'),
        description: 'Food',
        category: 'Food',
        subCategory: null,
        amount: 170,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-26T06:30:00.000Z'),
        description: 'Petrol',
        category: 'Fuel',
        subCategory: null,
        amount: 1298.7,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-27T06:30:00.000Z'),
        description: 'Mom',
        category: 'Medical',
        subCategory: null,
        amount: 1130,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-27T06:30:00.000Z'),
        description: 'Petrol Car',
        category: 'Fuel',
        subCategory: null,
        amount: 2537.75,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-27T06:30:00.000Z'),
        description: 'Clothes',
        category: 'Clothes',
        subCategory: null,
        amount: 2725,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-27T06:30:00.000Z'),
        description: 'Clothes',
        category: 'Clothes',
        subCategory: null,
        amount: 1972,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-28T06:30:00.000Z'),
        description: 'Tea',
        category: 'Misc',
        subCategory: null,
        amount: 60,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-30T06:30:00.000Z'),
        description: 'Pastry',
        category: 'Food',
        subCategory: null,
        amount: 180,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-30T06:30:00.000Z'),
        description: 'Car Insurance',
        category: 'Misc',
        subCategory: null,
        amount: 11897,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-30T06:30:00.000Z'),
        description: 'Jalebi',
        category: 'Food',
        subCategory: null,
        amount: 160,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-06-30T06:30:00.000Z'),
        description: 'NPS',
        category: 'Investment',
        subCategory: null,
        amount: 5000,
        type: 'EXPENSE',
        paymentMode: 'CASH',
        tags: ['june-import'],
        notes: null,
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-01T00:00:00.000Z'),
        description: 'Seerat Savings',
        category: 'Investment',
        subCategory: null,
        amount: 1000,
        type: 'EXPENSE',
        paymentMode: 'NET_BANKING',
        tags: [],
        notes: '',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-01T00:00:00.000Z'),
        description: 'Interest',
        category: 'Salary',
        subCategory: null,
        amount: 805,
        type: 'INCOME',
        paymentMode: 'NET_BANKING',
        tags: [],
        notes: '',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-02T00:00:00.000Z'),
        description: 'Mom Groceries',
        category: 'Groceries',
        subCategory: null,
        amount: 10000,
        type: 'EXPENSE',
        paymentMode: 'UPI',
        tags: [],
        notes: '5000 Cash and 5000 UPI',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-04T00:00:00.000Z'),
        description: 'Groww App',
        category: 'Salary',
        subCategory: null,
        amount: 72.64,
        type: 'INCOME',
        paymentMode: 'NET_BANKING',
        tags: [],
        notes: 'Return',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-04T00:00:00.000Z'),
        description: 'Electricity Bill',
        category: 'Utilities',
        subCategory: null,
        amount: 2812,
        type: 'EXPENSE',
        paymentMode: 'UPI',
        tags: [],
        notes: 'Electricity Bill',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-05T00:00:00.000Z'),
        description: 'ICICI EMI',
        category: 'Utilities',
        subCategory: null,
        amount: 28403,
        type: 'EXPENSE',
        paymentMode: 'NET_BANKING',
        tags: [],
        notes: 'ICICI EMI',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-05T00:00:00.000Z'),
        description: 'Lord Krishna EMI',
        category: 'Utilities',
        subCategory: null,
        amount: 6000,
        type: 'EXPENSE',
        paymentMode: 'NET_BANKING',
        tags: [],
        notes: 'Gagan EMI',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
      {
        userId: user.id,
        date: new Date('2026-07-05T00:00:00.000Z'),
        description: 'Chunni Lal',
        category: 'Food',
        subCategory: null,
        amount: 170,
        type: 'EXPENSE',
        paymentMode: 'UPI',
        tags: [],
        notes: 'Samose',
        recurring: false,
        attachments: [],
        accountId: account.id,
      },
    ],
  });
  console.log(`Seeded ${73} transactions.`);

  console.log('Database Seeding Complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
